#!/bin/bash

while : ; do
	if (( "$3" == 1 ))
		then
			gettime=$(ps -Hau | grep $2 | awk '{sum += $4} END {print sum}')
	elif (( "$3" == 2))
		then
			gettime=$(ps -Hau | grep $2 | awk '{sum += $4} END {print sum}')
	fi
	ontime=$(echo $gettime/100 | bc -l)
	offtime=$(echo '(100 - ontime)/100' | bc -l)
	echo 1 | sudo tee "$1"/brightness >/dev/null
	sleep $ontime
	echo 0 | sudo tee "$1"/brightness >/dev/null
	sleep $offtime
done 