#!/bin/bash

count=1
quit=0
folder=/sys/class/leds
declare -a folderarray
menu(){
    count=1
    echo "Welcome to the LED Configuration Menu!"
    echo "======================================"
    echo "Please select an LED to configure:"
    for dir in $(ls $folder);
    do 
		echo $count. $dir
		folderarray[$count]=$dir
		let count++
    done
    echo $count. "Quit"
}

submenu(){
	subquit=0
	while [ $subquit -eq 0 ]; do
		echo 
		echo "======================================"
		echo "What would you like to do with this LED?"
		echo "1) turn on"
		echo "2) turn off"
		echo "3) associate with a system event"
		echo "4) associate with the performance of a process"
		echo "5) stop association with a process' performance"
		echo "6) quit to main menu"
		echo "Please enter a number (1-6) for your choice: "
		read choice
		if
			
		elif [ $choice -eq 6 ]
			then
			quit=1
		else
			echo "Invalid option entered. Please enter again."
			echo ""
		fi
}

#Script Entry Point is here
while [ $quit -eq 0 ]; do
    menu
    read choice
    if ((1<=$choice && $choice<=$count-1))
		then
		submenu
		echo ""
    elif [ $choice -eq $count ]
		then
		quit=1
    else
		echo "Invalid option entered. Please enter again."
		echo ""
    fi
done
echo "Goodbye!"
